project:
  type: book
  output-dir: docs

language: _language-ukr.yml

book:
  title: "Моделювання складних систем у Python"
  author: 
    - name: Соловйов В.М
      orcid: 0000-0002-4945-202X
      url: https://kdpu.edu.ua/personal/vmsoloviov.html
      email: vnsoloviev2016@gmail.com
      affiliation: 
        - name: Криворізький державний педагогічний університет
          department: Фізики та методики її навчання
          city: Кривий Ріг
          state: Дніпропетровська область
          url: https://kdpu.edu.ua

    - name: Бєлінський А.О.
      orcid: 0000-0002-2821-2895
      url: https://www.duet.edu.ua/ua/persons/96
      email: krivogame@gmail.com
      affiliation: 
        - name: Державний університет економіки і технологій
          department: Економіки та цифрового бізнесу
          city: Кривий Ріг
          state: Дніпропетровська область
          url: https://www.duet.edu.ua/ua
  downloads: [docx]
  reader-mode: false
  date: today 
  cover-image: title_book.jpeg
  date-format: iso 
  search: true
  repo-url: https://github.com/Butman2099/Complex-systems-book
  repo-actions: [edit]
  site-url: https://butman2099.github.io/Complex-systems-book/
  chapters:
    - index.qmd
    - lab_1.ipynb
    - lab_2.ipynb
    - lab_3.ipynb
    - lab_4.ipynb
    - lab_5.ipynb
    - lab_6.ipynb
    - lab_7.ipynb
    - lab_8.ipynb
    - lab_9.ipynb
    - lab_10.ipynb
    - lab_11.ipynb
    - lab_12.ipynb
    - lab_13.ipynb
    - lab_14.ipynb
  appendices:
    - appa.ipynb
    - appb.ipynb
    - appc.ipynb
    - appd.ipynb
    - references.qmd

bibliography: references_main.bib
csl: physical-review-b.csl
toc: true
number-sections: true
callout-appearance: default

format:
  html:
    grid:
      body-width: 1050px
    highlight-style: arrow
    css: style.css
    page-layout: full
    theme:
      light: cosmo
      dark: superhero
  docx: 
    fontsize: 14
    toc: true
    number-sections: true
    




